# Generated by Django 4.0.4 on 2022-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'Название', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AddField(
            model_name='pricecard',
            name='pc_img',
            field=models.ImageField(default=1, upload_to='price_img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricecard',
            name='pc_description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
