# Generated by Django 4.0.4 on 2022-07-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_remove_designslid_design_id_designslid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designslid',
            name='id',
        ),
        migrations.AddField(
            model_name='designslid',
            name='design_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
