# Generated by Django 4.0.4 on 2022-07-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_remove_designslid_id_designslid_design_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designslid',
            name='design_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
