# Generated by Django 4.0.4 on 2022-07-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yawn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_city',
            field=models.CharField(default=1, max_length=200, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
